# Generated by Django 4.1.6 on 2023-03-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task',
            new_name='task_name',
        ),
    ]
